### ISSUE TITLE
Does it handle token expiration?

### ISSUE THREAD

**Issue by nimatullah** [serhiisol/ngx-auth#14]
What if  `JWT` token expired, what will happen?

**Comment by serhiisol** [comment]
Hi @nimatullah, basically library relies on correct backend response.
For example, once token got expired backend throws you 401 status and some specific error code that you can handle in `refreshShouldHappen` method of `AuthService`, also in this method you can analyse that request and make a decision whether token should be refreshed or not.

**Comment by nimatullah** [comment]
Ok, I will use the library, and if I stack on something then I will ask :)

**Comment by serhiisol** [comment]
Ok :)

**Comment by nimatullah** [comment]
@serhiisol, my angular version is `4.4.4`, should I use `ngx-auth@2.2.0` or the latest one?

**Comment by serhiisol** [comment]
check please README.md
