### ISSUE TITLE
JWT auth

### ISSUE THREAD

**Issue by kojibhy** [serhiisol/ngx-auth#16]
hi I can`t get how I need to overwrite 

` private getHeaders?(token: string): {
    [name: string]: string | string[];
  };`

to use JWT instead of Bearer , can someone help

**Comment by serhiisol** [comment]
Hi,

basically you need to create another method in your AuthService which will return object with your header, e.g.:
```typescript
/**
   * Add token to headers, dependent on server
   * set-up, by default adds a bearer token.
   * Called by interceptor.
   *
   * To change behavior, override this method.
   *
   * @public
   *
   * @param {string} token
   *
   * @returns {[name: string]: string | string[]}
   */
  public getHeaders(token: string) : { 
    return {
      'X-Auth': `Token ${token}`
    }
  };
```

**Comment by kojibhy** [comment]
i add something like this in my authentication.service.ts:
`
  getHeaders(token: string): any {
    return { Authorization: `JWT ${token}`};
  }`

and it start working Thx

**Comment by serhiisol** [comment]
no problem :)
