### ISSUE TITLE
PublicGuard and ProtectedGuard

### ISSUE THREAD

**Issue by rafaelvalerini** [serhiisol/ngx-auth#18]
Hi, 

Is it possible to use PublicGuard and ProtectedGuard for the same url? For even after logging in, the user can also access the public screens and this code not work:

```
{
        path:'user',
        canActivate: [ PublicGuard, ProtectedGuard ],
        component: LoginComponent
}
```

When trying to access the url `user`, nothing happens to the user logged.

I need a same screen can be accessed with the logged in user and also be accessed when the user is not yet logged in.

**Comment by serhiisol** [comment]
Hi @rafaelvalerini. What's the point of doing that ? If you want to give access to the page for all the users, just remove those guards completely :)
