### ISSUE TITLE
How to call refresh token from client side.

### ISSUE THREAD

**Issue by nimatullah** [serhiisol/ngx-auth#23]
Now, it calls when the response of server is `401`. What if it checks the token expiration and requests the refresh token before other requests in the client side?

I have implemented server side, and I want to implement the client side as well. I already have the function inside to check the expiration. it returns `true` or `false`.

**Comment by serhiisol** [comment]
well, I don't think you should worry about it on the client side, also adding extra library to the source code. Your server already handles that, so interceptor will receive right response.

**Comment by nimatullah** [comment]
Ok

**Comment by nimatullah** [comment]
Hi @serhiisol , 

I have two type of request : one happens with Authentication, and another request happens in without authentication.

For example, I have (website, admin, employer-panel).

- In admin and employer-panel are protected routes which work fine.

- In the website, some routes are protected and some routes are public. for example (setting, network, connection) are protected and (jobs-list, company-list, job-view, company-view ) are public routes.

In protected routes I get token expiration from server and then refresh routes call which is working find.

In public route, for example, I have viewd jobs, searched jobs, and keep busy for lets say 30 minutes. 

lets assume ,
token expire after 10 minutes.
reftesh token expires after 20 minutes.

after 25 minuts of  browsing  with public routes I wanna go back to protected routes. it logout me. becuase the token has expired and I was busy with public routes.

So my question is, how to handle refresh token in my public routes. Eventhough the token is appended to my every public reques. ?

Sorry my english is not good. 
I hope you understand my question .

Thanks

**Comment by serhiisol** [comment]
Hi @nimatullah. Thanks for the question, Yeah, I guess all the requests will have token added to the headers. So I guess we can add some sort of parameter to skip adding the header. Or we can add url as a parameter to `https://github.com/serhiisol/ngx-auth/blob/master/src/auth.service.ts#L54` to check, if url has to have token.
