### ISSUE TITLE
invalid login details bug

### ISSUE THREAD

**Issue by ankitparmar372** [serhiisol/ngx-auth#24]
while invalid credentials it also called refreshToken while login.

this.tokenStorage.getRefreshToken

**Comment by serhiisol** [comment]
Hi there, could you give me an example of the app so I can reproduce this issue? For me it seems like you have implemented wrong `refreshShouldHappen` method, which determines, whether refresh request should be executed or not.

**Comment by ankitparmar372** [comment]
Hey Serhiisol,
Thanks
I solved the issue using refresh should happen function by default false.
