### ISSUE TITLE
Custom interceptor

### ISSUE THREAD

**Issue by nicolasq92** [serhiisol/ngx-auth#27]
Is there a way to add or overwrite the operation of the interceptor? or to implement a custom interceptor?

I need to verify first if there is a token or not, to redirect it to the main page.

Thank you

**Comment by serhiisol** [comment]
For that reason you can use one of the guards provided by the package: `PublicGuard` for public routes and `ProtectedGuard` for protected.

**Comment by nicolasq92** [comment]
no. i already did that, and for some reason, sometimes, the request are sending without token. That why i want to put some validation on the interceptor

**Comment by serhiisol** [comment]
Check out your `AuthService` if it extract token properly.

**Comment by serhiisol** [comment]
No problem :)
