### ISSUE TITLE
Private guard remember URL

### ISSUE THREAD

**Issue by smnbbrv** [serhiisol/ngx-auth#28]
Hi,

the library is super, thank you for supporting this!

Question: is it possible to remember the URL that was attempted to be loaded and redirect to this URL after user logs in without extending / replacing the original `ProtectedGuard`?

This is dumb, but quite an important feature; it is even available in Angular guides: https://angular.io/guide/router#teach-authguard-to-authenticate

**Comment by serhiisol** [comment]
well, in theory you can extend `ProtectedGuard` and provide your own guard instead, like so:
```
{
  provide: ProtectedGuard,
  useClass: MyNewProtectedGuard
}
```

But otherwise, that might be a good addition to the library.
