### ISSUE TITLE
Unable to integrate with Spring Boot: getting "_a is null" and no tokens.

### ISSUE THREAD

**Issue by mcpierce** [serhiisol/ngx-auth#29]
I [posted about a problem I'm having ](https://stackoverflow.com/questions/51576811/unable-to-get-ngx-auth-to-work-with-spring-boot-rest-server-using-jwt-getting)with integration on StackOverflow. I wanted to file an issue here as well to see if we can find the solution.

TL;DR version:

I've written an AuthenticationService class for my Angular app that talks to my backend Spring Boot REST server. Authentication is working correctly in Java, and the JWT token is being returned in the response headers.

However, when the login method (which uses code from the examples on the ngx-auth website) gets the response, there are no access tokens present; i.e., there doesn't seem to be anything from the ngx-auth library intercepting or interpreting the headers and extracting the token.

Can you please advise what's potentially the problem? [Here](https://github.com/mcpierce/comixed/tree/feature/issue-110) is a link to the task branch on which I'm working to try and integrate the two.

**Comment by mcpierce** [comment]
The error as seen on Firefox relates to the access tokens being passed back to the authentication service. Running things on Chrome I see:

```TypeError: Cannot read property 'accessToken' of null```

going back to the call to saveAccessData() in my AuthenticationToken class below:

```
login(username: string, password: string): Observable<any> {
    return this.http.post('login', {email: username, password: password})
      .pipe(
      tap((tokens: AccessData) => {
        console.log('login tokens:', tokens);
        this.saveAccessData(tokens);
      }));
  }
```

Is there some setup outside of what's described on the Github page that needs to be done?

**Comment by serhiisol** [comment]
Hi @mcpierce. As far as I understood you have an issue with saving/reading tokens. Basically extraction and persisting processes rely on your implementation. So you have to check whether your saving/extracting tokens properly.

**Comment by mcpierce** [comment]
Yeah, the issue seems to be that, on the Java side, the SuccessfulAuthentication filter is never firing. And that is the portion that sends down the access and refresh tokens. So the problem's definitely not with ngx-auth.
