### ISSUE TITLE
Angular 7 build

### ISSUE THREAD

**Issue by St-Bun** [serhiisol/ngx-auth#37]
Hi,

When performing a production build (ng build --prod) using Angular 7 I get the following errors:

`ERROR in ./node_modules/ngx-auth/esm5/ngx-auth.js Module not found: Error: Can't resolve 'rxjs/Subject' in '\node_modules\ngx-auth\esm5' ERROR in ./node_modules/ngx-auth/esm5/ngx-auth.js Module not found: Error: Can't resolve 'rxjs/observable/throw' in '\node_modules\ngx-auth\esm5' ERROR in ./node_modules/ngx-auth/esm5/ngx-auth.js Module not found: Error: Can't resolve 'rxjs/operator/catch' in '\node_modules\ngx-auth\esm5' 
ERROR in ./node_modules/ngx-auth/esm5/ngx-auth.js Module not found: Error: Can't resolve 'rxjs/operator/first' in '\node_modules\ngx-auth\esm5' 
ERROR in ./node_modules/ngx-auth/esm5/ngx-auth.js Module not found: Error: Can't resolve 'rxjs/operator/map' in '\node_modules\ngx-auth\esm5' ERROR in ./node_modules/ngx-auth/esm5/ngx-auth.js Module not found: Error: Can't resolve 'rxjs/operator/switchMap' in '\node_modules\ngx-auth\esm5' 
ERROR in chunk main [initial] [name].[chunkhash:20].js \node_modules\@angular-devkit\build-optimizer\src\build-optimizer\webpack-loader.js??ref--17-0!\node_modules\@ngtools\webpack\src\index.js!\src\main.ts d43ecfaacdbac9efba5a77e422e96789 Unexpected token (104:34) | this.injector = injector; | this.refreshInProgress = false; | this.refreshSubject = new !(function webpackMissingModule() { var e = new Error("Cannot find module \"rxjs/Subject\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())(); | } | AuthInterceptor.prototype.intercept = function (req, delegate) {`

**Comment by serhiisol** [comment]
What's the version of `ngx-auth` that you use? It doesn't seem like you're using the latest one. We don't use `rxjs/Subject` anymore but we do use 
`import { Subject } from 'rxjs';`

**Comment by St-Bun** [comment]
Removed node_modules-folder and did a 'fresh' npm install.
It works again, thanks!

**Comment by serhiisol** [comment]
No problem, happy coding :D
