### ISSUE TITLE
How to set headers for http requests via refreshToken()

### ISSUE THREAD

**Issue by ujjaldey** [serhiisol/ngx-auth#41]
Hi,

Thanks for this awesome package. Really makes our lives simple.

One question. I noticed that when I call the refresh api through the refreshToken() function, it does not add the Authorization header in the request. My refresh api expects the token to be present in the header. Is there any way I can include the header when I am posting the request via refreshToken()? My code:

```
  public refreshToken(): Observable<any> {
    console.log('refreshToken');

    return this.tokenStorage
      .getAccessToken()
      .pipe(
        switchMap((refreshToken: string) =>
          this.http.post(`http://localhost/uku/api/auth/refresh`, {})
        ),
        tap((tokens: any) => {
          console.log(tokens);
          this.saveAccessData(tokens);
        }),
        catchError((err) => {
          this.logout();

          return Observable.throw(err);
        })
      );
  }
```

Header:
![image](https://user-images.githubusercontent.com/16843102/54825155-d3700100-4ce7-11e9-88e7-a8c56bb6cfce.png)

**Comment by serhiisol** [comment]
it should automatically refresh token if the previous request fails with access token failure.
First of all, you have to identify refresh token request, so the library won't intercept it and won't add extra refresh token functionality for particular request:
```typescript
  public verifyTokenRequest(url: string): boolean {
    return url.endsWith('refresh-token');
  }
```
then you have to tell library that previous request failed because of the access token failure:

```typescript
  public refreshShouldHappen(response: HttpErrorResponse): boolean {
    return response.status === 401; // for example at this point we need to refresh token
  }
```

**Comment by ujjaldey** [comment]
Yes. I have these functions in place. And I do see that the refresh api is getting called whenever the original request returns 401.

But my api does not return any refresh_token. It refreshes any expired token based on access_token only which I need to pass along with my '/refresh' call. But the refresh request does not seem to have the 'Authorization: Bearer' in the header. So my api is returning invalid token response. I have found a quick workaround. I can pass the token as query param with the url. But is there any better way!

```
public refreshToken(): Observable<any> {
 return this.tokenStorage
  .getAccessToken()
  .pipe(
	switchMap((accessToken: string) =>
	  this.http.post(`http://localhost/uku/api/auth/refresh?token=${accessToken}`, {})
	),
	tap((tokens: any) => {
	  this.saveAccessData(tokens.data.accessToken);
	}),
	catchError((err) => {
	  this.logout();
	  return Observable.throw(err);
	})
  );
}
```

**Comment by serhiisol** [comment]
if refresh token is verified properly via `verifyTokenRequest` interceptor won't add any tokens to the request, it won't process that request at all.
