### ISSUE TITLE
Angular 8 compatibility

### ISSUE THREAD

**Issue by ymanvieu** [serhiisol/ngx-auth#48]
hello,

I just upgrade to Angular 8.0.0 and having the following warnings:
```
warning " > ngx-auth@5.0.0" has incorrect peer dependency "@angular/core@^7.0.0".
warning " > ngx-auth@5.0.0" has incorrect peer dependency "@angular/compiler@^7.0.0".
warning " > ngx-auth@5.0.0" has incorrect peer dependency "@angular/router@^7.0.0".
warning " > ngx-auth@5.0.0" has incorrect peer dependency "@angular/common@^7.0.0".
```

ngx-auth seems to work anyway but can you take a look ?

thanks

**Comment by serhiisol** [comment]
Thanks for the issue, I'll push changes asap.

**Comment by sonusindhu** [comment]
Is there any updates on this issue @serhiisol ?

**Comment by serhiisol** [comment]
@sonusindhu sorry for delay, got laptop broken so I had to return it to the service shop to fix it

**Comment by serhiisol** [comment]
Released.
