### ISSUE TITLE
Security conciderations 

### ISSUE THREAD

**Issue by redaxmedia** [serhiisol/ngx-auth#52]
Hey,

just learned from a talk that tokens should not be stored in the browser. Therefore the example on README using localStorage is a bad practice...

There is an official statement by auth0:
https://auth0.com/docs/security/store-tokens#don-t-store-tokens-in-local-storage

At this moment I don't have a perfect solution, so I ask the community to find something.

This issue is not about blaming, I love this project.

**Comment by serhiisol** [comment]
Hi. Thanks for your feedback. In readme you've found only example :) Real implementation is up to you :)

**Comment by redaxmedia** [comment]
Most developers just follow this example and don't mind about the security. Like said, I am looking for a discussion to provide a better approach.

Was thinking about:

1. switch to sessionStorage in the example
2. provide helpers to encrypt and decrypt the storage (might be out of project scrope)

**Comment by serhiisol** [comment]
Well, examples just give you ideas how to integrate any sort of libraries into your code. But at the end you have to think with your own head :)

Anyway, feel free to send PRs, any help is appreciated

**Comment by redaxmedia** [comment]
Please change the example to secure cookies.

[Don't Store Tokens in Local Storage; Use Secure Cookies](https://dzone.com/articles/security-best-practices-for-managing-api-access-to)

**Comment by serhiisol** [comment]
This is just an example, shouldn't be considered for production
