### ISSUE TITLE
verifyRefreshToken receiving wrong parameter

### ISSUE THREAD

**Issue by alexjavier15** [serhiisol/ngx-auth#54]
The method verifyRefreshToken in AuthService is expecting an object of type HttpRequest

https://github.com/serhiisol/ngx-auth/blob/ee237f26622ea9aa5612c350c6f7a30ded4be1b7/src/auth.service.ts#L41

However, the interceptor is passing the request url sting
https://github.com/serhiisol/ngx-auth/blob/ee237f26622ea9aa5612c350c6f7a30ded4be1b7/src/auth.interceptor.ts#L169-L180

what ends up in the awful error

"Cannot read property 'endsWith' of undefined"

**Comment by serhiisol** [comment]
Hi @alexjavier15, good catch, I'll update library tonight.

**Comment by serhiisol** [comment]
Done :)

**Comment by alexjavier15** [comment]
Thank you very much! I'll check it out right away

**Comment by serhiisol** [comment]
No problem, I hope it will help you. Cheers :D
