### ISSUE TITLE
ERROR in node_modules/ngx-auth/auth.module.d.ts

### ISSUE THREAD

**Issue by kojibhy** [serhiisol/ngx-auth#56]
`0% compiling
Compiling ngx-auth : es2015 as esm2015

Date: 2020-02-27T11:38:51.911Z - Hash: ff00e8a5c9dc3162e009
6 unchanged chunks

Time: 3082ms

ERROR in Cannot read property 'push' of undefined
    
    ERROR in node_modules/ngx-auth/auth.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AuthenticationModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ngx-auth) which declares AuthModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    1 export declare class AuthModule {
                           ~~~~~~~~~~
    src/app/authentication/authentication.module.ts:31:14 - error NG6002: Appears in the NgModule.imports of CoreModule, but itself has errors
    31 export class AuthenticationModule {
                    ~~~~~~~~~~~~~~~~~~~~
    src/app/core/core.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of AppModule, but itself has errors
    28 export class CoreModule {
`

`$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.3
Node: 10.15.2
OS: linux x64

Angular: 9.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cdk                      9.1.0
@angular/material                 9.1.0
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
    
`

**Comment by serhiisol** [comment]
Hi @kojibhy this library has not been tested with later angular yet. I'm going to update it asap, but feel free to submit PR with adjustments. Thanks :)

**Comment by serhiisol** [comment]
Hi @kojibhy I just tried angular 9 and latest version of the `ngx-auth` and it actually works. Check it out here: https://github.com/serhiisol/ngx-auth-example
