### ISSUE TITLE
Refresh the token before making a new request

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [serhiisol/ngx-auth#59]
Hi,

Is it possible to check if it is needed to refresh the token before making a new request?
As you know, there is an expires_at field where it is sometimes better to check it and refresh the token before making a request.

the flow when making a new request:
1- check expires_at 
2- if expired, refresh and continue
3- make a request
4- if response is 401, refresh the token and retry

**Comment by serhiisol** [comment]
Hi @AhmedNourJamalElDin, yes we can add something like a pre-hook, to do validations.

**Comment by AhmedNourJamalElDin** [comment]
Hi @serhiisol 

Thanks for your response.
