### ISSUE TITLE
Angular 16 compatibility

### ISSUE THREAD

**Issue by dfabregaswefox** [serhiisol/ngx-auth#62]
Since Angular 16, View Engine libraries are incompatible, will you release a new version compatible with the Ivy engine?

**Comment by serhiisol** [comment]
@dfabregaswefox it will take a bit longer, since most of the libraries used in the project are outdated so I'm updating them.

**Comment by dfabregaswefox** [comment]
Thank you for taking care of this

**Comment by serhiisol** [comment]
@dfabregaswefox version 6 with support of angular 16 has been released.
