### ISSUE TITLE
Guards with CanLoad support

### ISSUE THREAD

**Issue by xdom** [serhiisol/ngx-auth#8]
It'd be great if both `ProtectedGuard` and `PublicGuard` implemented `CanLoad` interface, so we could use them also with lazy loaded modules.  What do you think?

**Comment by serhiisol** [comment]
@xdom seems like a great idea, but could you give an example ?

**Comment by xdom** [comment]
Unfortunately, this is a signature of `canLoad` method:
```
canLoad(route: Route): Observable<boolean> | Promise<boolean> | boolean;
```

So we cannot use route snapshot or router state parameters. Therefore we must omit `&& !this.isPublicPage(state)` check in `canLoad` method:
```js
public canLoad(route: Route): Observable<boolean> {
    return map(
      this.authService .isAuthorized(),
      (isAuthorized: boolean) => {

        if (!isAuthorized) {
          this.navigate(this.publicFallbackPageUri);
          return false;
        }

        return true;
      }
    );
  }
```

Is it still safe? Why are `isPublicPage`/`isProtectedPage` checks even there?

**Comment by serhiisol** [comment]
well :) that's what I meant just roughly :) I think we can do it)

**Comment by xdom** [comment]
However, I discovered there is currently an issue [angular#16197](https://github.com/angular/angular/issues/16197). So the proposed solution with `canLoad` won't work with your example where public fallback uri is `/`. This would be confusing for users who don't know about this issue. I would postpone this feature until someone from Angular fixes the mentioned issue.

**Comment by serhiisol** [comment]
Ok, I'll close for now, feel free to open
