### ISSUE TITLE
Angular V5 compatibility ? 

### ISSUE THREAD

**Issue by JulienBourgain** [serhiisol/ngx-auth#9]
When i do a "yarn start" of my application or of your example app with angular v5.0.1 and angular cli 1.5.0 (and rxjs 5.5.2 for angular 5) i've got this issue : 

```
ERROR in ./node_modules/ngx-auth/index.ts
Module build failed: Error: C:\Users\julien\ngx-auth-example\node_modules\ngx-auth\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\julien\ngx-auth-example\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (C:\Users\julien\ngx-auth-example\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app-routing.module.ts 9:0-55
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

```
I think, angular-cli doesn't compile TS files in node_modules anymore and before, it was a mistake : 
https://github.com/angular/angular-cli/issues/8284

So you can use somethink like this to fix that => https://github.com/dherges/ng-packagr

**Comment by serhiisol** [comment]
Hi @JulienBourgain, that's a good catch, I'll take a look at the PR.

**Comment by serhiisol** [comment]
Good news, I managed to solve this problem, I'll create PR soon

**Comment by serhiisol** [comment]
example application works with `aot` flag as well, https://github.com/serhiisol/ngx-auth-example
